prices<-Quandl("BSE/BSEMID", start_date=Sys.Date()-10000, end_date=Sys.Date(), type="xts")
chartSeries(prices[,1], theme=chartTheme('white'))
addMACD(fast = 12, slow = 26, signal = 9) 
# addMACD(fast = 5, slow = 15, signal = 7) 
addBBands() 
addSMI(n=13,slow=25,fast=2,signal=9,ma.type="EMA")
# addSMI(n=40,slow=75,fast=6,signal=9,ma.type="EMA")
# addADX(n = 40, maType="EMA", wilder=TRUE)
addADX(n = 14, maType="EMA", wilder=TRUE)
addRSI(n=40)
rsi<-RSI(prices[,c("Net Asset Value")])